import type { ToolGroup } from "./grouper.js";
import type { UpstreamTool } from "./discoverer.js";

/**
 * Generate a human-readable property description from a JSON Schema property definition.
 */
function describeProperty(
  name: string,
  schema: Record<string, unknown>
): string {
  const type = schema.type || "any";
  const description = schema.description ? ` — ${schema.description}` : "";
  const isRequired = schema._required ? " (required)" : " (optional)";
  return `\`${name}\` (${type}${isRequired})${description}`;
}

/**
 * Extract property definitions from a JSON Schema object.
 * Handles both flat and nested properties structures.
 */
function extractProperties(
  inputSchema: Record<string, unknown>
): { name: string; schema: Record<string, unknown> }[] {
  const properties = inputSchema.properties as
    | Record<string, Record<string, unknown>>
    | undefined;
  if (!properties) return [];

  const required =
    (inputSchema.required as string[]) || [];

  return Object.entries(properties).map(([name, schema]) => ({
    name,
    schema: { ...schema, _required: required.includes(name) },
  }));
}

/**
 * Generate a human-readable type string from a JSON Schema type.
 */
function schemaType(schema: Record<string, unknown>): string {
  const t = schema.type;
  if (Array.isArray(t)) return t.join(" | ");
  if (typeof t === "string") return t;
  return "any";
}

/**
 * Generate an example value for a property based on its schema type.
 */
function exampleValue(name: string, schema: Record<string, unknown>): string {
  const t = schemaType(schema);
  if (t === "number" || t === "integer") return "42";
  if (t === "boolean") return "true";
  // For strings, use the property name as a hint
  const lower = name.toLowerCase();
  if (lower.includes("path")) return '"/tmp/example.txt"';
  if (lower.includes("name")) return '"example-name"';
  if (lower.includes("id")) return '"abc-123"';
  if (lower.includes("url") || lower.includes("uri")) return '"https://example.com"';
  if (lower.includes("content") || lower.includes("text")) return '"Hello, world!"';
  if (lower.includes("query") || lower.includes("search")) return '"search terms"';
  return '"value"';
}

/**
 * Generate an example command string for a tool.
 */
function generateExample(tool: UpstreamTool): string {
  const props = extractProperties(tool.inputSchema);
  if (props.length === 0) return tool.name;

  const required = props.filter((p) => p.schema._required);
  const args: Record<string, string> = {};
  for (const p of required.slice(0, 3)) {
    args[p.name] = exampleValue(p.name, p.schema);
  }

  const argsStr = JSON.stringify(args);
  // Keep examples compact
  if (argsStr.length < 80) {
    return `${tool.name} ${argsStr}`;
  }
  return tool.name;
}

/**
 * Generate a complete help text for a tool group.
 */
export function generateHelpText(group: ToolGroup): string {
  const lines: string[] = [];

  lines.push(`⚡ MCPico — ${group.groupName}`);
  lines.push("");
  lines.push(
    `Source: ${group.serverName} (${group.tools.length} tool${group.tools.length === 1 ? "" : "s"})`
  );
  lines.push("");
  lines.push("Usage:  <subcommand> {" + '"}key{"}": {"}value{"}' + "}");
  lines.push(
    "        Send just 'help' to see this reference again."
  );
  lines.push("");
  lines.push("─".repeat(50));
  lines.push("");

  for (const tool of group.tools) {
    lines.push(`  ${tool.name}`);
    if (tool.description) {
      lines.push(`    ${tool.description}`);
    }
    lines.push("");

    const props = extractProperties(tool.inputSchema);
    if (props.length > 0) {
      lines.push("    Parameters:");
      for (const p of props) {
        lines.push(`      ${describeProperty(p.name, p.schema)}`);
      }
      lines.push("");
    }

    const example = generateExample(tool);
    lines.push(`    Example: ${example}`);
    lines.push("");
  }

  lines.push("─".repeat(50));
  lines.push(
    "Generated by MCPico — auto-updates when upstream tools change."
  );

  return lines.join("\n");
}
