import { describe, it, expect } from "vitest";
import { generateHelpText } from "./help.js";
import type { ToolGroup } from "./grouper.js";
import type { UpstreamTool } from "./discoverer.js";

function makeTool(overrides: Partial<UpstreamTool> = {}): UpstreamTool {
  return {
    name: "test_tool",
    description: "A test tool",
    inputSchema: {
      type: "object",
      properties: {
        param1: { type: "string", description: "First parameter" },
      },
      required: ["param1"],
    },
    ...overrides,
  };
}

function makeGroup(overrides: Partial<ToolGroup> = {}): ToolGroup {
  return {
    groupName: "test",
    serverName: "test-server",
    tools: [makeTool()],
    ...overrides,
  };
}

describe("generateHelpText", () => {
  it("includes group name in header", () => {
    const text = generateHelpText(makeGroup({ groupName: "filesystem" }));
    expect(text).toContain("MCPico — filesystem");
  });

  it("includes server name", () => {
    const text = generateHelpText(
      makeGroup({ serverName: "my-server" })
    );
    expect(text).toContain("my-server");
  });

  it("shows correct tool count", () => {
    const text = generateHelpText(makeGroup());
    expect(text).toContain("1 tool");
  });

  it("shows plural for multiple tools", () => {
    const group = makeGroup({
      tools: [makeTool({ name: "tool_a" }), makeTool({ name: "tool_b" })],
    });
    const text = generateHelpText(group);
    expect(text).toContain("2 tools");
  });

  it("includes usage instructions", () => {
    const text = generateHelpText(makeGroup());
    expect(text).toContain("Usage:");
    expect(text).toContain("<subcommand>");
    expect(text).toContain("Send just 'help'");
  });

  it("lists each tool by name", () => {
    const group = makeGroup({
      tools: [
        makeTool({ name: "read_file", description: "Read a file" }),
        makeTool({ name: "write_file", description: "Write a file" }),
      ],
    });
    const text = generateHelpText(group);
    expect(text).toContain("read_file");
    expect(text).toContain("Read a file");
    expect(text).toContain("write_file");
    expect(text).toContain("Write a file");
  });

  it("shows tool description", () => {
    const text = generateHelpText(
      makeGroup({
        tools: [makeTool({ description: "Does something useful" })],
      })
    );
    expect(text).toContain("Does something useful");
  });

  it("shows parameters section for tools with properties", () => {
    const text = generateHelpText(makeGroup());
    expect(text).toContain("Parameters:");
    expect(text).toContain("param1");
    expect(text).toContain("(string");
    expect(text).toContain("(required)");
    expect(text).toContain("First parameter");
  });

  it("marks optional parameters", () => {
    const tool = makeTool({
      inputSchema: {
        type: "object",
        properties: {
          optional_param: { type: "string", description: "Not required" },
        },
        required: [],
      },
    });
    const text = generateHelpText(makeGroup({ tools: [tool] }));
    expect(text).toContain("(optional)");
  });

  it("does not show Parameters section for tools without properties", () => {
    const tool = makeTool({
      inputSchema: { type: "object", properties: {} },
    });
    const text = generateHelpText(makeGroup({ tools: [tool] }));
    expect(text).not.toContain("Parameters:");
  });

  it("generates examples for tools with parameters", () => {
    const tool = makeTool({
      inputSchema: {
        type: "object",
        properties: {
          path: { type: "string", description: "File path" },
        },
        required: ["path"],
      },
    });
    const text = generateHelpText(makeGroup({ tools: [tool] }));
    expect(text).toContain("Example:");
    expect(text).toContain("/tmp/example.txt");
  });

  it("shows bare subcommand for parameterless tools", () => {
    const tool = makeTool({
      inputSchema: { type: "object", properties: {} },
    });
    const text = generateHelpText(makeGroup({ tools: [tool] }));
    expect(text).toContain("Example:");
    expect(text).toContain(tool.name);
  });

  it("includes footer", () => {
    const text = generateHelpText(makeGroup());
    expect(text).toContain("Generated by MCPico");
  });

  it("handles tools without descriptions", () => {
    const tool = makeTool({ description: undefined });
    const text = generateHelpText(makeGroup({ tools: [tool] }));
    expect(text).toContain(tool.name);
    // Should not crash — tool is still listed
  });

  it("generates smart example values for known parameter names", () => {
    const tool = makeTool({
      name: "search",
      inputSchema: {
        type: "object",
        properties: {
          query: { type: "string", description: "Search query" },
          limit: { type: "integer", description: "Max results" },
          url: { type: "string", description: "Target URL" },
        },
        required: ["query", "limit", "url"],
      },
    });
    const text = generateHelpText(makeGroup({ tools: [tool] }));
    expect(text).toContain("search terms");
    expect(text).toContain("42");
    expect(text).toContain("https://example.com");
  });

  it("handles tools with a mix of required and optional params in example", () => {
    const tool = makeTool({
      name: "write",
      inputSchema: {
        type: "object",
        properties: {
          path: { type: "string" },
          content: { type: "string" },
          encoding: { type: "string" },
        },
        required: ["path"],
      },
    });
    const text = generateHelpText(makeGroup({ tools: [tool] }));
    // Example should show the required param
    expect(text).toContain("path");
    expect(text).toContain("/tmp/example.txt");
  });

  it("handles tools with no inputSchema", () => {
    const tool = makeTool({ inputSchema: {} });
    const text = generateHelpText(makeGroup({ tools: [tool] }));
    expect(text).toContain(tool.name);
    // Should not crash
  });
});
